env: "local"
port: 4444
timeout: 1m
postgres:
  host: "localhost"
  SQLPort: 5432
  user: "postgres"
  password: "password"
  DBName: "banner_test"
  sslMode: "disable"
  driver: "pgx"
redis:
  address: "localhost:6379"
  password: "5379"
  DB: 0
  TTLMinutes: 5m