version: '3'
services:
  postgres:
    image: postgres:latest
    hostname: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banner_test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5432

  redis:
    image: redis:latest
    hostname: "redis"
    ports:
      - "6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: banner_test
    depends_on:
      - postgres
      - redis
    environment:
      CONFIG_PATH: /config/stage.yaml
    ports:
      - "4444:4444"
    volumes:
      - ./internal/configure/stage.yaml:/config/stage.yaml

volumes:
  postgres_data:
